### ISSUE TITLE
wla-gb silent fails with non-opcode symbols?

### ISSUE THREAD

**Issue by nicklausw** [vhelin/wla-dx#112]
In the process of converting an RGBDS project to WLA...

```
include "src/gb.i"
```

WLA just stops right here.  Returns quietly in Cygwin and Command Prompt when I know this is an error.

**Comment by nicklausw** [comment]
Does the hashmap thingy know to give an error when things don't work?

**Comment by nicklausw** [comment]
Wait, not the hashmaps. Still can't figure this out.

**Comment by nicklausw** [comment]
It has something to do with failure with loose quotes, which I thought was fixed before.

**Comment by vhelin** [comment]
Do you still get this behavior? I tried to replicate the issue, but there isn't much info about it...

**Comment by nicklausw** [comment]
That's the entirety of the issue. If your wla gives an error for a loose include then I guess it's been fixed. If it doesn't then something's up. I probably don't actually have the file where the error happened anymore.

**Comment by nicklausw** [comment]
I should mention that I'm not at a computer right now, otherwise I'd test this myself.

**Comment by vhelin** [comment]
I just tried to include a file that doesn't exist and WLA gives me a clear error about it. Do you still get a silent exit without any error messages in a similar situation in Cygwin (or elsewhere)?

I remember there was a bug that was fixed by adding a fflush() to directive_print() - the printed string didn't appear on screen in Cygwin - perhaps this is similar and we could fix this by adding fflush() to print_error()?
