### ISSUE TITLE
Make WLA's and WLALINK's version information contain the GitHub version number

### ISSUE THREAD

**Issue by vhelin** [vhelin/wla-dx#20]
... or build number, or version date, whatever works best.

**Comment by cr1901** [comment]
Let me think about this... since development uses git (and therefore any changes need to be committed on a system with git installed), there shouldn't be any issue running a command to create as pre or post-commit hook, that the main WLA binary includes to get its version info. Even better, if the current commit is a tag, then the build-number can be replaced with a version number.

**Comment by vhelin** [comment]
Sounds good! WLA's build scripts could be written to do the job, if the
version info is available inside some local file, etc., I don't really
know, but if you have the energy to take care of this - thanks! :)


On Fri, Jan 30, 2015 at 12:03 PM, William D. Jones <notifications@github.com

**Comment by vhelin** [comment]
After quite a few years this hasn't been an issue so I guess I'll close this one.
