### ISSUE TITLE
SMS: romsize computation

### ISSUE THREAD

**Issue by HerrSchatten** [vhelin/wla-dx#332]
After updating to v9.11, when compiling I get the message:

"COMPUTE_SMS_CHECKSUM: Defined ROMSIZE $0 (256KBs) is bigger than the ROM image (128KBs) itself."

Is .SMSHEADER a compulsory directive all of a sudden? So far I had always just used .SDSCTAG and left it to handle the header information automatically, which I found quite convenient. I don't think I've explicitly defined a romsize before. Is that necessary now?

**Comment by vhelin** [comment]
We get that $0 (256KBs) from $1FFF/$3FFF/$7FFF. Which is where .SMSHEADER puts these days the ROM size. That 128KBs comes from the actual file size. This was touched 03-Apr-2020. Previously it just calculated the checksum from $0000 to SMS header.

I guess it should be modified so that it doesn't read the defined ROM size from the SMS header if it's not defined...

If you now try the latest sources, will it work as before?

**Comment by HerrSchatten** [comment]
That seems to have worked, thank you.
