### ISSUE TITLE
What's the purpose of WLA's temporary files?

### ISSUE THREAD

**Issue by nicklausw** [vhelin/wla-dx#44]
Okay, this question was stupid but I have another question: why not simplify generate_tmp_names() so that the file made doesn't depend on OS? I changed it so it's always "wla_a.tmp" and "wla_b.tmp", and removed the "-DMSDOS" from my makefile. The binaries work perfectly. Perhaps this could make it so that there can be a universal makefile (and a separate one just for Amiga)?

**Comment by cr1901** [comment]
WLA generates temporary files because between pass 2 and 3 and 4  because WLA doesn't actually immediately generate an object file, but a temporary text file that contains information about data types and placement.

"Why not simplify generate_tmp_names() so that the file made doesn't depend on OS?"
Because it works fine as is. If you're on a Unix system, the calls that generate_tmp_names() made to unistd.h are guaranteed to exist. So I never felt the need to change it.

"Perhaps this could make it so that there can be a universal makefile (and a separate one just for Amiga)?" That's what CMake is for. :) Also -DMSDOS should be there just in case it makes a difference in the future.
